# Generated by Django 2.1.5 on 2019-04-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190404_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdfview',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
